### ISSUE TITLE
Localize Database Connections/Cursor Usage

### ISSUE THREAD

**Issue by ncloudioj** [matthewruttley/zenko#1]
In Zenko, all database queries are executed via two global connections/cursors. That might unnecessarily hold the connection resources and prevent other applications from accessing the database.

Better localize the connection usage, like create a new connection while executing a new query, and close it immediately once you're done using this connection. For example,

``` python
cursor = conn.cursor()
try:
   cursor.execute(...)
except:
   # error handling here
else:
   # do your stuff here
finally:
   cursor.close()
```

**Comment by matthewruttley** [comment]
Fixed in the most recent commit :)
I've abstracted it to a different function which opens and closes the connection when making a query: https://github.com/matthewruttley/zenko/commit/e47023800380f53ede1e6db2cce35cdfaec4155e
